import codecs

with codecs.open("index.html", "r", encoding="utf-8") as f:
    text = f.read()

replacements = {
    '[DE] Industrial Safety Monitoring System': 'Industrielles Sicherheitsüberwachungssystem',
    '[DE] ML-Driven Apiculture Monitoring': 'ML-gestützte Imkerei-Überwachung',
    '[DE] Agricultural Surveillance Drone': 'Agrarüberwachungsdrohne',
    '[DE] Container SBOM &amp; Attestation Tool': 'Container-SBOM &amp; Attestierungs-Tool',
    '[DE] Surgical Simulation Feedback Pipeline': 'Feedback-Pipeline für chirurgische Simulation',
    '[DE] PDF RAG Chatbot': 'PDF-RAG-Chatbot',
    '[DE] Student Analytics Chatbot': 'Studenten-Analyse-Chatbot',
    '[DE] Real-time computer vision safety enforcement for construction sites': 'Echtzeit-Computer-Vision-Sicherheitsdurchsetzung für Baustellen',
    '[DE] Computer Vision': 'Computer Vision',
    '[DE] ⚠️ Problem': '⚠️ Problem',
    '[DE] Construction and industrial sites contain hazardous zones where worker entry causes serious accidents. Traditional safety measures rely on manual supervision and physical barriers — slow, expensive, and error-prone.': 'Bau- und Industriestandorte enthalten Gefahrenzonen, in denen das Betreten durch Arbeiter schwere Unfälle verursacht. Traditionelle Sicherheitsmaßnahmen verlassen sich auf manuelle Überwachung und physische Barrieren — langsam, teuer und fehleranfällig.',
    '[DE] ⚙️ Solution': '⚙️ Lösung',
    '[DE] Built a YOLOv5-based computer vision system that monitors live video feeds, defines programmable virtual safety boundaries using ROI and bounding boxes, and detects workers crossing into restricted zones in real time. Triggers instant visual/audio alerts on violation.': 'Ein YOLOv5-basiertes Computer-Vision-System entwickelt, das Live-Videofeeds überwacht, programmierbare virtuelle Sicherheitsgrenzen mit ROI und Bounding Boxes definiert und Arbeiter, die in Echtzeit in gesperrte Zonen eintreten, erkennt. Löst sofortige visuelle/akustische Alarme bei Verstößen aus.',
    '[DE] ✅ Outcome': '✅ Ergebnis',
    '[DE] Deployed as a cost-effective system compatible with existing camera infrastructure. Presented as a research paper at ICICC 2025 (Paper ID: 1346). Designed to scale across different site layouts without additional hardware.': 'Als kostengünstiges System eingesetzt, das mit bestehender Kamerainfrastruktur kompatibel ist. Als Forschungsarbeit auf der ICICC 2025 präsentiert (Paper ID: 1346). Für die Skalierung über verschiedene Standortlayouts ohne zusätzliche Hardware ausgelegt.',
    '[DE] YOLOv5': 'YOLOv5',
    '[DE] Object Detection': 'Objekterkennung',
    '[DE] ROI-based Boundary Mapping': 'ROI-basierte Grenzenkartierung',
    '[DE] Real-time Video Analysis': 'Echtzeit-Videoanalyse',
    '[DE] Alert Systems': 'Alarmsysteme',
    '[DE] ML-Driven Apiculture Monitoring System': 'ML-gestütztes Imkerei-Überwachungssystem',
    '[DE] Multi-modal edge AI for intelligent beehive health monitoring': 'Multimodale Edge-KI zur intelligenten Bienenstock-Gesundheitsüberwachung',
    '[DE] Edge AI': 'Edge-KI',
    '[DE] Bee populations are declining globally. Traditional hive monitoring relies on manual inspections — infrequent, disruptive, and unable to catch fast-moving threats like predator attacks or colony collapse disorder early enough.': 'Bienenpopulationen nehmen weltweit ab. Die traditionelle Stocküberwachung basiert auf manuellen Inspektionen — selten, störend und nicht in der Lage, schnell auftretende Bedrohungen wie Räuberangriffe oder das Bienensterben frühzeitig zu erkennen.',
    '[DE] Built a two-module edge AI system: (1) A YOLO-based predator detection module running on Jetson Nano that identifies hornets and wasps around hives in real time. (2) A CNN + BiLSTM acoustic model that continuously analyzes hive sounds to detect colony stress, abnormal behaviour, and estimate honey yield — all without opening the hive.': 'Ein zweistufiges Edge-KI-System entwickelt: (1) Ein YOLO-basiertes Räubererkennungsmodul auf dem Jetson Nano, das Hornissen und Wespen rund um die Bienenstöcke in Echtzeit identifiziert. (2) Ein akustisches CNN + BiLSTM-Modell, das kontinuierlich Stockgeräusche analysiert, um Kolonniestress, anormales Verhalten zu erkennen und den Honigertrag zu schätzen — alles ohne den Stock zu öffnen.',
    '[DE] Filed as a patent (Application No: 202441071459). Received a ₹10 lakh government grant from the Government of Andhra Pradesh for further development. Non-invasive, continuous monitoring with no cloud dependency.': 'Als Patent angemeldet (Anmeldenummer: 202441071459). Ein staatliches Stipendium von ₹10 Lakh von der Regierung von Andhra Pradesh für die Weiterentwicklung erhalten. Nicht-invasive, kontinuierliche Überwachung ohne Cloud-Abhängigkeit.',
    '[DE] CNN': 'CNN',
    '[DE] BiLSTM': 'BiLSTM',
    '[DE] Deep Learning': 'Deep Learning',
    '[DE] Jetson Nano': 'Jetson Nano',
    '[DE] Microphone Sensors': 'Mikrofonsensoren',
    '[DE] Camera Modules': 'Kameramodule',
    '[DE] Edge Inference': 'Edge-Inferenz',
    '[DE] Acoustic Analysis': 'Akustische Analyse',
    '[DE] Custom-built drone for aerial farm monitoring and surveillance': 'Selbstgebaute Drohne zur Luftüberwachung landwirtschaftlicher Flächen',
    '[DE] Robotics': 'Robotik',
    '[DE] Manual field inspections are time-consuming and physically demanding for farmers, especially across large land areas. Existing commercial drones are expensive and not tailored to specific agricultural needs.': 'Manuelle Feldinspektionen sind zeitaufwendig und körperlich anspruchsvoll für Landwirte, besonders auf großen Flächen. Vorhandene kommerzielle Drohnen sind teuer und nicht auf spezifische landwirtschaftliche Bedürfnisse zugeschnitten.',
    '[DE] Designed and assembled a drone from components, studying aerodynamics, Bernoulli\'s principle, and flight dynamics (pitch, roll, yaw). Integrated sensors and electronics to enable stable flight and aerial field surveillance for agricultural monitoring use cases.': 'Eine Drohne aus Komponenten entworfen und zusammengebaut, dabei Aerodynamik, das Bernoulli-Prinzip und Flugdynamik (Nicken, Rollen, Gieren) studiert. Sensoren und Elektronik integriert, um stabilen Flug und Luftfeldüberwachung für landwirtschaftliche Überwachungsanwendungen zu ermöglichen.',
    '[DE] Functional drone prototype with stable flight characteristics. Demonstrated understanding of full hardware stack from frame assembly to flight controller integration. Foundation for future precision agriculture applications.': 'Funktionsfähiger Drohnenprototyp mit stabilen Flugeigenschaften. Verständnis des vollständigen Hardware-Stacks vom Rahmenaufbau bis zur Flugsteuerungsintegration nachgewiesen. Grundlage für zukünftige Präzisionslandwirtschaftsanwendungen.',
    '[DE] Drone Frame': 'Drohnenrahmen',
    '[DE] Flight Controller': 'Flugsteuerung',
    '[DE] ESCs': 'ESCs',
    '[DE] Brushless Motors': 'Bürstenlose Motoren',
    '[DE] Aerodynamics': 'Aerodynamik',
    '[DE] Flight Dynamics': 'Flugdynamik',
    '[DE] Sensor Integration': 'Sensorintegration',
    '[DE] Electronics Assembly': 'Elektronikaufbau',
    '[DE] Agricultural Monitoring': 'Landwirtschaftliche Überwachung',
    '[DE] Container SBOM &amp; Attestation Analysis Tool': 'Container-SBOM &amp; Attestierungsanalyse-Tool',
    '[DE] Automated container compliance verification and Excel reporting pipeline': 'Automatisierte Container-Compliance-Verifizierung und Excel-Berichtspipeline',
    '[DE] DevOps': 'DevOps',
    '[DE] Enterprise software teams struggle to track what packages are running inside container images at scale, making compliance audits slow and error-prone when done manually.': 'Enterprise-Softwareteams haben Schwierigkeiten, im großen Maßstab zu verfolgen, welche Pakete in Container-Images laufen, was Compliance-Audits bei manueller Durchführung langsam und fehleranfällig macht.',
    '[DE] Built a Bash/Python pipeline that verifies container images using cosign attestations, extracts full package metadata from SBOMs, compares expected vs detected versions, flags mismatches, and auto-generates multi-sheet Excel compliance reports with summaries, highlights, and metrics.': 'Eine Bash/Python-Pipeline entwickelt, die Container-Images mit cosign-Attestierungen verifiziert, vollständige Paketmetadaten aus SBOMs extrahiert, erwartete mit erkannten Versionen vergleicht, Konflikte markiert und mehrseitige Excel-Compliance-Berichte mit Zusammenfassungen, Hervorhebungen und Metriken automatisch generiert.',
    '[DE] Deployed as part of GitLab CI/CD pipelines at MyCom. Reduced manual compliance checking time significantly. Reports used directly in internal audits.': 'Als Teil der GitLab-CI/CD-Pipelines bei MyCom eingesetzt. Manuelle Compliance-Prüfungszeit deutlich reduziert. Berichte direkt in internen Audits verwendet.',
    '[DE] cosign': 'cosign',
    '[DE] Excel Automation': 'Excel-Automatisierung',
    '[DE] Compliance Reporting': 'Compliance-Berichterstellung',
    '[DE] LLM-powered coach feedback system for VR surgical training': 'LLM-gestütztes Coach-Feedback-System für VR-Chirurgietraining',
    '[DE] AI / NLP': 'KI / NLP',
    '[DE] Surgical trainees using VR simulators receive raw performance metric data (XML logs) with no structured interpretation — making it hard to understand what went wrong and how to improve.': 'Chirurgie-Auszubildende, die VR-Simulatoren nutzen, erhalten rohe Leistungsmetrikdaten (XML-Protokolle) ohne strukturierte Interpretation — was es schwer macht zu verstehen, was schiefgelaufen ist und wie man sich verbessern kann.',
    '[DE] Built a Python pipeline that parses PerfMetrics XML logs from VR surgical simulators, feeds structured data into LLMs (OpenAI/Gemini), and generates detailed coach-style feedback reports in Markdown/HTML — covering step-wise analysis, error identification, and improvement recommendations.': 'Eine Python-Pipeline entwickelt, die PerfMetrics-XML-Protokolle von VR-Chirurgiesimulator parst, strukturierte Daten in LLMs (OpenAI/Gemini) einspeist und detaillierte Coach-Stil-Feedback-Berichte in Markdown/HTML generiert — mit schrittweiser Analyse, Fehleridentifikation und Verbesserungsempfehlungen.',
    '[DE] Integrated into Simulatory AG\'s VRSpine Pro training platform. Enabled automated, scalable feedback generation for surgical trainees. Cost-efficient token usage through careful prompt engineering.': 'In Simulatory AGs VRSpine Pro-Trainingsplattform integriert. Automatisierte, skalierbare Feedback-Generierung für Chirurgie-Auszubildende ermöglicht. Kosteneffiziente Token-Nutzung durch sorgfältiges Prompt Engineering.',
    '[DE] OpenAI API': 'OpenAI API',
    '[DE] Gemini API': 'Gemini API',
    '[DE] Prompt Engineering': 'Prompt Engineering',
    '[DE] XML Parsing': 'XML-Parsing',
    '[DE] Markdown/HTML Reports': 'Markdown/HTML-Berichte',
    '[DE] LLM Pipelines': 'LLM-Pipelines',
    '[DE] Semantic document Q&amp;A chatbot using retrieval-augmented generation': 'Semantischer Dokument-Q&amp;A-Chatbot mit Retrieval-Augmented Generation',
    '[DE] NLP / RAG': 'NLP / RAG',
    '[DE] Users working with large PDF documents (reports, manuals, research papers) have no way to quickly query specific information — they\'re forced to read manually or use basic keyword search.': 'Nutzer, die mit großen PDF-Dokumenten (Berichte, Handbücher, Forschungsarbeiten) arbeiten, haben keine Möglichkeit, spezifische Informationen schnell abzufragen — sie sind gezwungen, manuell zu lesen oder eine einfache Schlüsselwortsuche zu verwenden.',
    '[DE] Built a RAG pipeline using LangChain, FAISS vector store, and Gemini-2.0-Flash that ingests PDFs via PyMuPDF, generates semantic embeddings, and answers natural language questions by retrieving and synthesizing relevant document chunks.': 'Eine RAG-Pipeline mit LangChain, FAISS-Vektorspeicher und Gemini-2.0-Flash entwickelt, die PDFs via PyMuPDF aufnimmt, semantische Embeddings generiert und natürliche Sprachfragen beantwortet, indem relevante Dokumentenabschnitte abgerufen und synthetisiert werden.',
    '[DE] Functional chatbot deployable locally or via API. Supports multi-document querying. Accurate, contextual answers grounded in source documents — not hallucinated.': 'Funktionsfähiger Chatbot, der lokal oder über API einsetzbar ist. Unterstützt Multi-Dokument-Abfragen. Genaue, kontextuelle Antworten, die in Quelldokumenten verankert sind — keine Halluzinationen.',
    '[DE] LangChain': 'LangChain',
    '[DE] FAISS': 'FAISS',
    '[DE] Gemini-2.0-Flash': 'Gemini-2.0-Flash',
    '[DE] Google Generative AI Embeddings': 'Google Generative AI Embeddings',
    '[DE] PyMuPDF': 'PyMuPDF',
    '[DE] RAG Architecture': 'RAG-Architektur',
    '[DE] Vector Search': 'Vektorsuche',
    '[DE] RAG-powered academic performance and placement analytics chatbot': 'RAG-gestützter Chatbot für akademische Leistungs- und Vermittlungsanalysen',
    '[DE] Academic institutions have placement and performance data stored in databases but no easy way for staff or students to query it conversationally — requiring manual SQL queries or spreadsheet analysis.': 'Akademische Einrichtungen haben Vermittlungs- und Leistungsdaten in Datenbanken gespeichert, aber keine einfache Möglichkeit für Mitarbeiter oder Studenten, diese konversationell abzufragen — was manuelle SQL-Abfragen oder Tabellenanalysen erfordert.',
    '[DE] Built a RAG-powered chatbot integrated with a Supabase database that answers natural language queries about student placement trends, academic performance, failure analysis, and training recommendations. Supports USN-level queries and aggregate summaries.': 'Einen RAG-gestützten Chatbot entwickelt, der mit einer Supabase-Datenbank integriert ist und natürliche Sprachanfragen zu Studentenvermittlungstrends, akademischer Leistung, Fehleranalyse und Trainingsempfehlungen beantwortet. Unterstützt USN-Abfragen und aggregierte Zusammenfassungen.',
    '[DE] Deployed for internal academic analytics use. Enables non-technical staff to query complex datasets through conversation. Surfaces actionable insights like weak areas by batch and placement patterns by company.': 'Für interne akademische Analysezwecke eingesetzt. Ermöglicht nicht-technischem Personal, komplexe Datensätze durch Konversation abzufragen. Zeigt verwertbare Erkenntnisse wie schwache Bereiche nach Jahrgang und Vermittlungsmuster nach Unternehmen auf.',
    '[DE] RAG': 'RAG',
    '[DE] Supabase (PostgreSQL)': 'Supabase (PostgreSQL)',
    '[DE] Analytics Dashboard': 'Analyse-Dashboard',
    '[DE] NLP Query Interface': 'NLP-Abfrageoberfläche'
}


for k, v in replacements.items():
    text = text.replace(f'data-de="{k}"', f'data-de="{v}"')
    text = text.replace(f'data-de-html="{k}"', f'data-de-html="{v}"')

with codecs.open("index.html", "w", encoding="utf-8") as f:
    f.write(text)

print("Updates applied to Project sections successfully.")
